### PR TITLE
el7.2/one4.14.2: fix gem rpm package creation (mini_portile2)

### PR DESCRIPTION
**Pull request by hoonetorg**

### CODE REVIEW

**Comment by hoonetorg** [comment]
Probably it's enough to install only rubygem mini_portile2 and remove mini_portile, but I did not test.
Also the build failed when not specifying the version.

**Comment by alvarosimon** [comment]
Great! thanks a lot, and sorry for the late reply. I was quite busy the last weeks. I have tested this in our VMs and works fine.

**Comment by hoonetorg** [comment]
I still needed to fix something after putting the packages in a local rpm repo, because I got conflicts and dependency problems.

**Comment by hoonetorg** [comment]
```
--- install_gems.orig   2015-11-25 20:38:25.000000000 +0100
+++ install_gems        2016-01-14 21:27:10.177177104 +0100
@@ -12,10 +12,12 @@ end

 if !defined?(RUBY_VERSION) || RUBY_VERSION < '1.9.0'
     $nokogiri='nokogiri --version "< 1.6.0"'
+    $mini_portile='mini_portile'
     LDAP='net-ldap --version "< 0.9"'
     ZENDESK_API='zendesk_api --version "< 1.5"'
 else
     $nokogiri='nokogiri'
+    $mini_portile='mini_portile2 --version "= 2.0.0.rc2"'
     DEFAULT = DEFAULT_PRE + %w{hybrid}
     LDAP='net-ldap'
     ZENDESK_API='zendesk_api'
@@ -231,13 +233,13 @@ def help
 end

 def which_gems(packages)
-    ([$nokogiri]+packages.map do |package|
+    ([$mini_portile]+[$nokogiri]+packages.map do |package|
         GROUPS[package.to_sym]
     end).flatten.uniq
 end

 def get_gems(packages)
-    ([$nokogiri]+packages.map do |package|
+    ([$mini_portile]+[$nokogiri]+packages.map do |package|
        GROUPS[package.to_sym]
     end).flatten.uniq-installed_gems
 end
```

**Comment by hoonetorg** [comment]
It seems there is something wrong with the deps of nokogiri regarding mini_portile2.
the script builds me 
rubygem-mini_portile2-2.0.0-1.noarch.rpm 
but 
nokogiri rpm wants
rubygem-mini_portile2-2.0.0.2-1.noarch.rpm (which is actually 2.0.0.rc2).
After some weird trying and copying the rubygem-mini_portile2-2.0.0.2-1.noarch.rpm to the local rpm repo instead of the rubygem-mini_portile2-2.0.0-1.noarch.rpm, all rubygem rpm's install correctly.

**Comment by alvarosimon** [comment]
Mmm... strange, I have to try this in my testbed. Which OS are you trying right now, CentOS7.2?

**Comment by alvarosimon** [comment]
@hoonetorg btw if you have problems installing a gem you can disable the package generation from the script. In this case nokogiri gem package is already installed by OpenNebula so you can remove it from the rpm list. just edit the exclude_gems
> exclude_gems = ['nokogiri']
and remove the nokogiri rpm in your repo, that will fix this issue

**Comment by hoonetorg** [comment]
i have the packages already :), probably for 4.16 or 5.0

**Comment by hoonetorg** [comment]
ah yes: CentOS 7.2

**Pull request merged**
